/*
# Visų klasių curriculum (iš CSV)
*/

DELETE FROM curriculum_subtopics;
DELETE FROM curriculum_topics;

INSERT INTO curriculum_topics (grade, slug, title, sort_order) VALUES
  (1, '1-zingsnis-i-pirmaja-klase', 'Žingsnis į pirmąją klasę', 1),
  (1, '1-sudetis-ir-atimtis-nuo-0-iki-9', 'Sudėtis ir atimtis nuo 0 iki 9', 2),
  (1, '1-skaiciai-iki-20', 'Skaičiai iki 20', 3),
  (1, '1-geometrija', 'Geometrija', 4),
  (1, '1-matavimai', 'Matavimai', 5),
  (1, '1-skaiciai-ir-veiksmai-iki-100', 'Skaičiai ir veiksmai iki 100', 6),
  (1, '1-laikas-ir-pinigai', 'Laikas ir pinigai', 7),
  (1, '1-duomenys-ir-desningumai', 'Duomenys ir dėsningumai', 8),
  (2, '2-skaiciai-iki-100-ir-veiksmai', 'Skaičiai iki 100 ir veiksmai', 1),
  (2, '2-daugyba', 'Daugyba', 2),
  (2, '2-dalyba', 'Dalyba', 3),
  (2, '2-veiksmu-eilute', 'Veiksmų eilutė', 4),
  (2, '2-geometrija', 'Geometrija', 5),
  (2, '2-matavimo-vienetai', 'Matavimo vienetai', 6),
  (2, '2-skaiciai-iki-1000', 'Skaičiai iki 1000', 7),
  (2, '2-tekstiniai-uzdaviniai-su-matavimo-vienetais', 'Tekstiniai uždaviniai su matavimo vienetais', 8),
  (3, '3-skaiciavimai-iki-1000', 'Skaičiavimai iki 1000', 1),
  (3, '3-paprastosios-trupmenos', 'Paprastosios trupmenos', 2),
  (3, '3-sudetis-ir-atimtis-iki-10000', 'Sudėtis ir atimtis iki 10000', 3),
  (3, '3-geometrija', 'Geometrija', 4),
  (3, '3-matavimo-vienetai', 'Matavimo vienetai', 5),
  (3, '3-pinigai', 'Pinigai', 6),
  (3, '3-daugyba-ir-dalyba-iki-10000', 'Daugyba ir dalyba iki 10000', 7),
  (3, '3-lygtys', 'Lygtys', 8),
  (3, '3-raidiniai-reiskiniai', 'Raidiniai reiškiniai', 9),
  (4, '4-skaiciavimai-iki-100000', 'Skaičiavimai iki 100000', 1),
  (4, '4-misrieji-skaiciai', 'Mišrieji skaičiai', 2),
  (4, '4-desimtaines-trupmenos', 'Dešimtainės trupmenos', 3),
  (4, '4-geometrija-2d', 'Geometrija (2D)', 4),
  (4, '4-stereometrija-3d', 'Stereometrija (3D)', 5),
  (4, '4-skaiciai-iki-1000000', 'Skaičiai iki 1000000', 6),
  (4, '4-lygtys-ir-nelygybes', 'Lygtys ir nelygybės', 7),
  (4, '4-matai-ir-matavimai', 'Matai ir matavimai', 8),
  (5, '5-naturalieji-skaiciai', 'Natūralieji skaičiai', 1),
  (5, '5-paprastosios-trupmenos-ir-misrieji-sk', 'Paprastosios trupmenos ir mišrieji sk.', 2),
  (5, '5-desimtainiai-sk-ir-procentai', 'Dešimtainiai sk. ir procentai', 3),
  (5, '5-reiskiniai-ir-lygtys', 'Reiškiniai ir lygtys', 4),
  (5, '5-geometrija-2d', 'Geometrija (2D)', 5),
  (5, '5-stereometrija-3d', 'Stereometrija (3D)', 6),
  (6, '6-sveikieji-skaiciai', 'Sveikieji skaičiai', 1),
  (6, '6-racionalieji-skaiciai', 'Racionalieji skaičiai', 2),
  (6, '6-lygus-trikampiai', 'Lygūs trikampiai', 3),
  (6, '6-veiksmai-su-racionaliaisiais-sk', 'Veiksmai su racionaliaisiais sk.', 4),
  (6, '6-tiesioginis-proporcingumas', 'Tiesioginis proporcingumas', 5),
  (6, '6-lygtys', 'Lygtys', 6),
  (6, '6-finansiniai-skaiciavimai', 'Finansiniai skaičiavimai', 7),
  (6, '6-geometrija-ir-mastelis', 'Geometrija ir mastelis', 8),
  (6, '6-duomenys-ir-tikimybes', 'Duomenys ir tikimybės', 9),
  (7, '7-laipsniai', 'Laipsniai', 1),
  (7, '7-nelygybes', 'Nelygybės', 2),
  (7, '7-atvirkstinis-proporcingumas', 'Atvirkštinis proporcingumas', 3),
  (7, '7-geometrijos-elementai', 'Geometrijos elementai', 4),
  (7, '7-keturkampiai', 'Keturkampiai', 5),
  (7, '7-plotai-ir-kiti-dydziai', 'Plotai ir kiti dydžiai', 6),
  (7, '7-stereometrija-3d', 'Stereometrija (3D)', 7),
  (7, '7-duomenys', 'Duomenys', 8),
  (7, '7-finansiniai-skaiciavimai', 'Finansiniai skaičiavimai', 9),
  (8, '8-saknys', 'Šaknys', 1),
  (8, '8-vektoriai', 'Vektoriai', 2),
  (8, '8-finansiniai-skaiciavimai', 'Finansiniai skaičiavimai', 3),
  (8, '8-reiskiniai', 'Reiškiniai', 4),
  (8, '8-geometrija', 'Geometrija', 5),
  (8, '8-sarysiai', 'Sąryšiai', 6),
  (8, '8-lygciu-sistemos', 'Lygčių sistemos', 7),
  (8, '8-stereometrija-3d', 'Stereometrija (3D)', 8),
  (8, '8-duomenys', 'Duomenys', 9),
  (9, '9-kvadratines-lygtys', 'Kvadratinės lygtys', 1),
  (9, '9-lygciu-sistemos', 'Lygčių sistemos', 2),
  (9, '9-trupmeniniai-reiskiniai', 'Trupmeniniai reiškiniai', 3),
  (9, '9-staciojo-trikampio-trigonometrija', 'Stačiojo trikampio trigonometrija', 4),
  (9, '9-apskritimo-geometrija', 'Apskritimo geometrija', 5),
  (9, '9-paprastos-funkcijos', 'Paprastos funkcijos', 6),
  (9, '9-kvadratines-funkcijos', 'Kvadratinės funkcijos', 7),
  (9, '9-skaiciu-sekos', 'Skaičių sekos', 8),
  (9, '9-statistika', 'Statistika', 9),
  (10, '10-proporcingieji-dydziai', 'Proporcingieji dydžiai', 1),
  (10, '10-racionaliosios-lygtys', 'Racionaliosios lygtys', 2),
  (10, '10-lygciu-sistemos', 'Lygčių sistemos', 3),
  (10, '10-kvadratines-nelygybes', 'Kvadratinės nelygybės', 4),
  (10, '10-panasios-figuros', 'Panašios figūros', 5),
  (10, '10-ibreztiniai-ir-apibreztiniai', 'Įbrėžtiniai ir apibrėžtiniai', 6),
  (10, '10-trigonometrija', 'Trigonometrija', 7),
  (10, '10-tikimybes-ir-kombinatorika', 'Tikimybės ir kombinatorika', 8),
  (10, '10-duomenys', 'Duomenys', 9),
  (11, '11-skaiciavimai', 'Skaičiavimai', 1),
  (11, '11-trigonometriniai-skaiciavimai', 'Trigonometriniai skaičiavimai', 2),
  (11, '11-progresijos', 'Progresijos', 3),
  (11, '11-funkcijos', 'Funkcijos', 4),
  (11, '11-lygtys', 'Lygtys', 5),
  (11, '11-nelygybes', 'Nelygybės', 6),
  (11, '11-vektoriai', 'Vektoriai', 7),
  (12, '12-trigonometrija', 'Trigonometrija', 1),
  (12, '12-isvestines', 'Išvestinės', 2),
  (12, '12-integralai', 'Integralai', 3),
  (12, '12-stereometrija-3d', 'Stereometrija (3D)', 4),
  (12, '12-tikimybes-ir-kombinatorika', 'Tikimybės ir kombinatorika', 5)
ON CONFLICT (grade, slug) DO UPDATE SET
  title = EXCLUDED.title,
  sort_order = EXCLUDED.sort_order;

INSERT INTO curriculum_subtopics (topic_id, slug, title, sort_order)
SELECT t.id, s.slug, s.title, s.ord
FROM curriculum_topics t
JOIN (VALUES
  (1, '1-zingsnis-i-pirmaja-klase', 'skaiciai-nuo-0-iki-9-rasymas-seka-desningumai', 'Skaičiai nuo 0 iki 9 (rašymas, seka, dėsningumai)', 1),
  (1, '1-zingsnis-i-pirmaja-klase', 'palyginimas', 'Palyginimas', 2),
  (1, '1-sudetis-ir-atimtis-nuo-0-iki-9', 'sudetis', 'Sudėtis', 1),
  (1, '1-sudetis-ir-atimtis-nuo-0-iki-9', 'atimtis', 'Atimtis', 2),
  (1, '1-sudetis-ir-atimtis-nuo-0-iki-9', 'sudeties-ir-atimties-tekstiniai-uzdaviniai', 'Sudėties ir atimties tekstiniai uždaviniai', 3),
  (1, '1-skaiciai-iki-20', 'skaiciai-11-20-ir-ju-sandara', 'Skaičiai 11–20 ir jų sandara', 1),
  (1, '1-skaiciai-iki-20', 'sudetis-ir-atimtis-neperzengiant-desimties', 'Sudėtis ir atimtis neperžengiant dešimties', 2),
  (1, '1-skaiciai-iki-20', 'sudetis-ir-atimtis-perzengiant-desimti', 'Sudėtis ir atimtis peržengiant dešimtį', 3),
  (1, '1-skaiciai-iki-20', 'skaiciu-palyginimas-ir-tekstiniai-uzdaviniai', 'Skaičių palyginimas ir tekstiniai uždaviniai', 4),
  (1, '1-geometrija', 'ploksciosios-figuros', 'Plokščiosios figūros', 1),
  (1, '1-geometrija', 'erdviniai-kunai', 'erdviniai kūnai', 2),
  (1, '1-geometrija', 'linijos-atkarpos-ir-simetrija', 'Linijos, atkarpos ir simetrija', 3),
  (1, '1-matavimai', 'ilgio-matavimas', 'Ilgio matavimas', 1),
  (1, '1-matavimai', 'mase', 'Masė', 2),
  (1, '1-matavimai', 'talpa', 'Talpa', 3),
  (1, '1-skaiciai-ir-veiksmai-iki-100', 'desimtys-ir-skaiciavimas-desimtimis-iki-100', 'Dešimtys ir skaičiavimas dešimtimis iki 100', 1),
  (1, '1-skaiciai-ir-veiksmai-iki-100', 'pilnu-desimciu-sudetis-ir-atimtis', 'Pilnų dešimčių sudėtis ir atimtis', 2),
  (1, '1-skaiciai-ir-veiksmai-iki-100', 'skaiciu-iki-100-palyginimas', 'Skaičių iki 100 palyginimas', 3),
  (1, '1-laikas-ir-pinigai', 'laikas', 'Laikas', 1),
  (1, '1-laikas-ir-pinigai', 'pinigai', 'Pinigai', 2),
  (1, '1-duomenys-ir-desningumai', 'rusiavimas-lenteles-ir-stulpelines-diagramos', 'Rūšiavimas, lentelės ir stulpelinės diagramos', 1),
  (2, '2-skaiciai-iki-100-ir-veiksmai', 'nezinomas-skaicius', 'Nežinomas skaičius', 1),
  (2, '2-skaiciai-iki-100-ir-veiksmai', 'sudetis-ir-atimtis-eilute', 'Sudėtis ir atimtis eilute', 2),
  (2, '2-skaiciai-iki-100-ir-veiksmai', 'sudetis-ir-atimtis-stulpeliu', 'Sudėtis ir atimtis stulpeliu', 3),
  (2, '2-skaiciai-iki-100-ir-veiksmai', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 4),
  (2, '2-daugyba', 'daugyba-kaip-vienodu-demenu-sudetis', 'Daugyba (kaip vienodų dėmenų sudėtis)', 1),
  (2, '2-daugyba', 'daugyba-is-2-5', 'Daugyba iš 2-5', 2),
  (2, '2-daugyba', 'daugyba-is-0-ir1', 'Daugyba iš 0 ir1', 3),
  (2, '2-daugyba', 'daugyba-is-6-10', 'Daugyba iš 6-10', 4),
  (2, '2-daugyba', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 5),
  (2, '2-dalyba', 'daugybos-ir-dalybos-rysys', 'Daugybos ir dalybos ryšys', 1),
  (2, '2-dalyba', 'dalyba-is-2', 'Dalyba iš 2', 2),
  (2, '2-dalyba', 'dalyba-is-3-ir-4', 'Dalyba iš 3 ir 4', 3),
  (2, '2-dalyba', 'lyginiai-nelyginiai-sk', 'Lyginiai, nelyginiai sk.', 4),
  (2, '2-dalyba', 'dalyba-is-5', 'Dalyba iš 5', 5),
  (2, '2-dalyba', 'dalyba-is-6-9', 'Dalyba iš 6-9', 6),
  (2, '2-dalyba', 'dalyba-is-1-ir-10', 'Dalyba iš 1 ir 10', 7),
  (2, '2-veiksmu-eilute', 'veiksmu-tvarka', 'Veiksmų tvarka', 1),
  (2, '2-veiksmu-eilute', 'reiskinys-su-skliaustais', 'Reiškinys su skliaustais', 2),
  (2, '2-veiksmu-eilute', 'visas-skaicius-kai-zinoma-jo-dalis', 'Visas skaičius, kai žinoma jo dalis', 3),
  (2, '2-veiksmu-eilute', 'kiti-tekstiniai-uzdaviniai', 'Kiti tekstiniai uždaviniai', 4),
  (2, '2-geometrija', 'kampai-ir-daugiakampiai', 'Kampai ir daugiakampiai', 1),
  (2, '2-geometrija', 'daugiakampiu-perimetras', 'Daugiakampių perimetras', 2),
  (2, '2-geometrija', 'simetrija', 'Simetrija', 3),
  (2, '2-matavimo-vienetai', 'ilgio', 'Ilgio', 1),
  (2, '2-matavimo-vienetai', 'mases', 'Masės', 2),
  (2, '2-matavimo-vienetai', 'talpos', 'Talpos', 3),
  (2, '2-matavimo-vienetai', 'laiko', 'Laiko', 4),
  (2, '2-skaiciai-iki-1000', 'sudetis', 'Sudėtis', 1),
  (2, '2-skaiciai-iki-1000', 'atimtis', 'Atimtis', 2),
  (2, '2-skaiciai-iki-1000', 'dvieju-zingsniu-tekstiniai-uzdaviniai', 'Dviejų žingsnių tekstiniai uždaviniai', 3),
  (2, '2-tekstiniai-uzdaviniai-su-matavimo-vienetais', 'ilgio', 'Ilgio', 1),
  (2, '2-tekstiniai-uzdaviniai-su-matavimo-vienetais', 'mases', 'Masės', 2),
  (2, '2-tekstiniai-uzdaviniai-su-matavimo-vienetais', 'talpos', 'Talpos', 3),
  (3, '3-skaiciavimai-iki-1000', 'sudetis', 'Sudėtis', 1),
  (3, '3-skaiciavimai-iki-1000', 'atimtis', 'Atimtis', 2),
  (3, '3-skaiciavimai-iki-1000', 'daugyba', 'Daugyba', 3),
  (3, '3-skaiciavimai-iki-1000', 'dalyba', 'Dalyba', 4),
  (3, '3-skaiciavimai-iki-1000', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 5),
  (3, '3-paprastosios-trupmenos', 'paprastoji-trupmena', 'Paprastoji trupmena', 1),
  (3, '3-paprastosios-trupmenos', 'skaiciaus-dalies-skaiciavimas', 'Skaičiaus dalies skaičiavimas', 2),
  (3, '3-paprastosios-trupmenos', 'palyginimas', 'Palyginimas', 3),
  (3, '3-paprastosios-trupmenos', 'viso-skaiciaus-ieskojimas', 'Viso skaičiaus ieškojimas', 4),
  (3, '3-paprastosios-trupmenos', 'kiti-tekstiniai-uzdaviniai', 'Kiti tekstiniai uždaviniai', 5),
  (3, '3-sudetis-ir-atimtis-iki-10000', 'apvalinimas', 'Apvalinimas', 1),
  (3, '3-sudetis-ir-atimtis-iki-10000', 'sudetis', 'Sudėtis', 2),
  (3, '3-sudetis-ir-atimtis-iki-10000', 'atimtis', 'Atimtis', 3),
  (3, '3-sudetis-ir-atimtis-iki-10000', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 4),
  (3, '3-geometrija', 'apskritimas', 'Apskritimas', 1),
  (3, '3-geometrija', 'staciakampis-gretasienis', 'Stačiakampis gretasienis', 2),
  (3, '3-geometrija', 'piramide', 'Piramidė', 3),
  (3, '3-geometrija', 'prizme', 'Prizmė', 4),
  (3, '3-geometrija', 'daugiakampio-perimetras', 'Daugiakampio perimetras', 5),
  (3, '3-matavimo-vienetai', 'ilgio', 'Ilgio', 1),
  (3, '3-matavimo-vienetai', 'mases', 'Masės', 2),
  (3, '3-matavimo-vienetai', 'talpos', 'Talpos', 3),
  (3, '3-matavimo-vienetai', 'laiko', 'Laiko', 4),
  (3, '3-daugyba-ir-dalyba-iki-10000', 'daugyba-ir-dalyba-is-apvaliu-sk', 'Daugyba ir dalyba iš apvalių sk.', 1),
  (3, '3-daugyba-ir-dalyba-iki-10000', 'daugyba-is-vienzenklio', 'Daugyba iš vienženklio', 2),
  (3, '3-daugyba-ir-dalyba-iki-10000', 'dalyba-su-liekana', 'Dalyba su liekana', 3),
  (3, '3-daugyba-ir-dalyba-iki-10000', 'dalyba-is-vienazenklio', 'Dalyba iš vienaženklio', 4),
  (3, '3-daugyba-ir-dalyba-iki-10000', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 5),
  (3, '3-lygtys', 'sudetis', 'Sudėtis', 1),
  (3, '3-lygtys', 'atimtis', 'Atimtis', 2),
  (3, '3-lygtys', 'daugyba', 'Daugyba', 3),
  (3, '3-lygtys', 'dalyba', 'Dalyba', 4),
  (3, '3-lygtys', 'lygties-sudarymas', 'Lygties sudarymas', 5),
  (3, '3-raidiniai-reiskiniai', 'reiskinio-apskaiciavimas', 'Reiškinio apskaičiavimas', 1),
  (3, '3-raidiniai-reiskiniai', 'reiskinio-sudarymas', 'Reiškinio sudarymas', 2),
  (4, '4-skaiciavimai-iki-100000', 'sudetis', 'Sudėtis', 1),
  (4, '4-skaiciavimai-iki-100000', 'atimtis', 'Atimtis', 2),
  (4, '4-skaiciavimai-iki-100000', 'daugyba', 'Daugyba', 3),
  (4, '4-skaiciavimai-iki-100000', 'dalyba', 'Dalyba', 4),
  (4, '4-skaiciavimai-iki-100000', 'veiksmu-eilute', 'Veiksmų eilutė', 5),
  (4, '4-skaiciavimai-iki-100000', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 6),
  (4, '4-misrieji-skaiciai', 'apvalinimas', 'Apvalinimas', 1),
  (4, '4-misrieji-skaiciai', 'paprastuju-trupmenu-sudetis-ir-atimtis', 'Paprastųjų trupmenų sudėtis ir atimtis', 2),
  (4, '4-misrieji-skaiciai', 'misriuju-skaiciu-sudetis-ir-atimtis', 'Mišriųjų skaičių sudėtis ir atimtis', 3),
  (4, '4-desimtaines-trupmenos', 'vertimas-i-paprasta-trupmena-ir-atvirksciai', 'Vertimas į paprastą trupmeną ir atvirkščiai', 1),
  (4, '4-desimtaines-trupmenos', 'sudetis-ir-atimtis', 'Sudėtis ir atimtis', 2),
  (4, '4-desimtaines-trupmenos', 'daugyba-ir-dalyba', 'Daugyba ir dalyba', 3),
  (4, '4-geometrija-2d', 'staciakampio-ir-kvadrato-plotas', 'Stačiakampio ir kvadrato plotas', 1),
  (4, '4-geometrija-2d', 'trikampiu-rusys', 'Trikampių rūšys', 2),
  (4, '4-geometrija-2d', 'perimetrai-ir-plotai', 'Perimetrai ir plotai', 3),
  (4, '4-skaiciai-iki-1000000', 'sudetis', 'Sudėtis', 1),
  (4, '4-skaiciai-iki-1000000', 'atimtis', 'Atimtis', 2),
  (4, '4-skaiciai-iki-1000000', 'daugyba', 'Daugyba', 3),
  (4, '4-skaiciai-iki-1000000', 'dalyba', 'Dalyba', 4),
  (4, '4-skaiciai-iki-1000000', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 5),
  (4, '4-lygtys-ir-nelygybes', 'lygtys', 'Lygtys', 1),
  (4, '4-lygtys-ir-nelygybes', 'nelygybes', 'Nelygybės', 2),
  (4, '4-lygtys-ir-nelygybes', 'judejimo-uzdaviniai', 'Judėjimo uždaviniai', 3),
  (4, '4-matai-ir-matavimai', 'veiksmai', 'Veiksmai', 1),
  (4, '4-matai-ir-matavimai', 'pinigai', 'Pinigai', 2),
  (4, '4-matai-ir-matavimai', 'ilgio-vnt', 'Ilgio vnt', 3),
  (4, '4-matai-ir-matavimai', 'laiko-vnt', 'laiko vnt.', 4),
  (4, '4-matai-ir-matavimai', 'turio-vnt', 'Tūrio vnt.', 5),
  (4, '4-matai-ir-matavimai', 'mases-vnt', 'Masės vnt.', 6),
  (5, '5-naturalieji-skaiciai', 'veiksmai', 'Veiksmai', 1),
  (5, '5-naturalieji-skaiciai', 'palyginimas', 'Palyginimas', 2),
  (5, '5-naturalieji-skaiciai', 'apvalinimas', 'Apvalinimas', 3),
  (5, '5-naturalieji-skaiciai', 'romeniski-skaitmenys', 'Romėniški skaitmenys', 4),
  (5, '5-naturalieji-skaiciai', 'dalumo-pozymiai', 'Dalumo požymiai', 5),
  (5, '5-naturalieji-skaiciai', 'dalikliai-ir-kartotiniai', 'Dalikliai ir kartotiniai', 6),
  (5, '5-naturalieji-skaiciai', 'pirminiai-ir-sudetiniai-sk', 'Pirminiai ir sudėtiniai sk.', 7),
  (5, '5-naturalieji-skaiciai', 'atskliaudimas-ir-veiksmu-eilutes', 'Atskliaudimas ir veiksmų eilutės', 8),
  (5, '5-naturalieji-skaiciai', 'skaidymas-pirminiais-dauginamaisiais', 'Skaidymas pirminiais dauginamaisiais', 9),
  (5, '5-paprastosios-trupmenos-ir-misrieji-sk', 'netaisyklingosios-trupmenos', 'Netaisyklingosios trupmenos', 1),
  (5, '5-paprastosios-trupmenos-ir-misrieji-sk', 'pertvarkymai', 'Pertvarkymai', 2),
  (5, '5-paprastosios-trupmenos-ir-misrieji-sk', 'palyginimas', 'Palyginimas', 3),
  (5, '5-paprastosios-trupmenos-ir-misrieji-sk', 'sudetis-ir-atimtis', 'Sudėtis ir atimtis', 4),
  (5, '5-paprastosios-trupmenos-ir-misrieji-sk', 'daugyba-ir-dalyba', 'Daugyba ir dalyba', 5),
  (5, '5-paprastosios-trupmenos-ir-misrieji-sk', 'misriuju-skaiciu-sudetis-ir-atimtis', 'Mišriųjų skaičių sudėtis ir atimtis', 6),
  (5, '5-paprastosios-trupmenos-ir-misrieji-sk', 'misriuju-skaiciu-daugyba-ir-dalyba', 'Mišriųjų skaičių daugyba ir dalyba', 7),
  (5, '5-desimtainiai-sk-ir-procentai', 'desimtainiai-skaiciai', 'Dešimtainiai skaičiai', 1),
  (5, '5-desimtainiai-sk-ir-procentai', 'desimtainiu-sk-palyginimas-ir-apvalinimas', 'Dešimtainių sk. palyginimas ir apvalinimas', 2),
  (5, '5-desimtainiai-sk-ir-procentai', 'procentai', 'Procentai', 3),
  (5, '5-desimtainiai-sk-ir-procentai', 'veiksmai-su-desimtainiais-sk', 'Veiksmai su dešimtainiais sk.', 4),
  (5, '5-desimtainiai-sk-ir-procentai', 'dalies-ir-visumos-radimas', 'Dalies ir visumos radimas', 5),
  (5, '5-desimtainiai-sk-ir-procentai', 'procentu-skaiciavimas', 'Procentų skaičiavimas', 6),
  (5, '5-reiskiniai-ir-lygtys', 'sekos', 'Sekos', 1),
  (5, '5-reiskiniai-ir-lygtys', 'raidiniai-reiskiniai', 'Raidiniai reiškiniai', 2),
  (5, '5-reiskiniai-ir-lygtys', 'lygtys', 'Lygtys', 3),
  (5, '5-reiskiniai-ir-lygtys', 'judejimo-uzdaviniai', 'Judėjimo uždaviniai', 4),
  (5, '5-geometrija-2d', 'ilgio-vienetai', 'Ilgio vienetai', 1),
  (5, '5-geometrija-2d', 'ploto-vienetai', 'Ploto vienetai', 2),
  (5, '5-geometrija-2d', 'kampai', 'Kampai', 3),
  (5, '5-geometrija-2d', 'kvadrato-ir-staciakampio-perimetras-ir-plotas', 'Kvadrato ir stačiakampio perimetras ir plotas', 4),
  (5, '5-geometrija-2d', 'staciojo-trikampio-plotas', 'Stačiojo trikampio plotas', 5),
  (5, '5-geometrija-2d', 'perimetrai-ir-plotai', 'Perimetrai ir plotai', 6),
  (5, '5-stereometrija-3d', 'turio-vienetai', 'Tūrio vienetai', 1),
  (5, '5-stereometrija-3d', 'staciakampis-gretasienis', 'Stačiakampis gretasienis', 2),
  (5, '5-stereometrija-3d', 'kubas', 'Kubas', 3),
  (6, '6-sveikieji-skaiciai', 'sveikieji-skaiciai-ir-ju-palyginimas', 'Sveikieji skaičiai ir jų palyginimas', 1),
  (6, '6-sveikieji-skaiciai', 'sudetis-ir-atimtis', 'Sudėtis ir atimtis', 2),
  (6, '6-sveikieji-skaiciai', 'daugyba-ir-dalyba', 'Daugyba ir dalyba', 3),
  (6, '6-sveikieji-skaiciai', 'koordinaciu-sistema', 'Koordinačių sistema', 4),
  (6, '6-racionalieji-skaiciai', 'racionalieji-skaiciai-ir-ju-palyginimas', 'Racionalieji skaičiai ir jų palyginimas', 1),
  (6, '6-racionalieji-skaiciai', 'trupmena-kaip-dalmuo', 'Trupmena kaip dalmuo', 2),
  (6, '6-racionalieji-skaiciai', 'begaliniai-skaiciai', 'Begaliniai skaičiai', 3),
  (6, '6-lygus-trikampiai', 'lygus-trikampiai-ir-ju-pozymiai', 'Lygūs trikampiai ir jų požymiai', 1),
  (6, '6-lygus-trikampiai', 'trikampio-egzistavimo-taisykle', 'Trikampio egzistavimo taisyklė', 2),
  (6, '6-veiksmai-su-racionaliaisiais-sk', 'daugyba', 'Daugyba', 1),
  (6, '6-veiksmai-su-racionaliaisiais-sk', 'dalyba', 'Dalyba', 2),
  (6, '6-veiksmai-su-racionaliaisiais-sk', 'sudetis', 'Sudėtis', 3),
  (6, '6-veiksmai-su-racionaliaisiais-sk', 'atimtis', 'Atimtis', 4),
  (6, '6-veiksmai-su-racionaliaisiais-sk', 'veiksmu-eilute', 'Veiksmų eilutė', 5),
  (6, '6-veiksmai-su-racionaliaisiais-sk', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 6),
  (6, '6-tiesioginis-proporcingumas', 'tiesiogiai-proporcingi-dydziai-ir-ju-grafikas', 'Tiesiogiai proporcingi dydžiai ir jų grafikas', 1),
  (6, '6-tiesioginis-proporcingumas', 'proporcija-ir-jos-savybe', 'Proporcija ir jos savybė', 2),
  (6, '6-tiesioginis-proporcingumas', 'procentu-uzdaviniai', 'Procentų uždaviniai', 3),
  (6, '6-lygtys', 'raidiniai-reiskiniai', 'Raidiniai reiškiniai', 1),
  (6, '6-lygtys', 'lygciu-sprendimas', 'Lygčių sprendimas', 2),
  (6, '6-lygtys', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 3),
  (6, '6-geometrija-ir-mastelis', 'mastelis', 'Mastelis', 1),
  (6, '6-geometrija-ir-mastelis', 'panasios-figuros', 'Panašios figūros', 2),
  (6, '6-geometrija-ir-mastelis', 'panasieji-trikampiai', 'Panašieji trikampiai', 3),
  (6, '6-geometrija-ir-mastelis', 'keturkampiu-kampu-suma', 'Keturkampių kampų suma', 4),
  (6, '6-duomenys-ir-tikimybes', 'vidurkis', 'Vidurkis', 1),
  (6, '6-duomenys-ir-tikimybes', 'moda-ir-mediana', 'Moda ir mediana', 2),
  (6, '6-duomenys-ir-tikimybes', 'diagramos', 'Diagramos', 3),
  (6, '6-duomenys-ir-tikimybes', 'galimybiu-medis', 'Galimybių medis', 4),
  (6, '6-duomenys-ir-tikimybes', 'daugybos-taisykle', 'Daugybos taisyklė', 5),
  (6, '6-duomenys-ir-tikimybes', 'tiketinumas', 'Tikėtinumas', 6),
  (7, '7-laipsniai', 'laipsnio-kelimas', 'Laipsnio kėlimas', 1),
  (7, '7-laipsniai', 'laipsniu-su-vienodais-pagrindai-daugyba-ir-dalyba', 'Laipsnių su vienodais pagrindai daugyba ir dalyba', 2),
  (7, '7-laipsniai', 'laipsniu-su-vienodais-rodikliais-daugyba-ir-dalyba', 'Laipsnių su vienodais rodikliais daugyba ir dalyba', 3),
  (7, '7-laipsniai', 'laipsnio-kelimas-laipsniu', 'Laipsnio kėlimas laipsniu', 4),
  (7, '7-laipsniai', 'laipsnis-su-sveikuoju-rodikliu', 'Laipsnis su sveikuoju rodikliu', 5),
  (7, '7-laipsniai', 'veiksmai-su-laipsniais', 'Veiksmai su laipsniais', 6),
  (7, '7-laipsniai', 'standartine-israiska', 'Standartinė išraiška', 7),
  (7, '7-nelygybes', 'savybes-ir-intervalai', 'Savybės ir intervalai', 1),
  (7, '7-nelygybes', 'nelygybiu-sprendimas', 'Nelygybių sprendimas', 2),
  (7, '7-nelygybes', 'nelygybiu-sistemos', 'Nelygybių sistemos', 3),
  (7, '7-nelygybes', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 4),
  (7, '7-geometrijos-elementai', 'pusiaukampine', 'Pusiaukampinė', 1),
  (7, '7-geometrijos-elementai', 'pusiaukrastine', 'Pusiaukraštinė', 2),
  (7, '7-geometrijos-elementai', 'aukstine', 'Aukštinė', 3),
  (7, '7-geometrijos-elementai', 'tiesiu-tarpusavio-padetys', 'Tiesių tarpusavio padėtys', 4),
  (7, '7-geometrijos-elementai', 'tiesiu-lygiagretumo-pozymiai', 'Tiesių lygiagretumo požymiai', 5),
  (7, '7-keturkampiai', 'lygiagretainis', 'Lygiagretainis', 1),
  (7, '7-keturkampiai', 'staciakampis', 'Stačiakampis', 2),
  (7, '7-keturkampiai', 'rombas', 'Rombas', 3),
  (7, '7-keturkampiai', 'kvadratas', 'Kvadratas', 4),
  (7, '7-keturkampiai', 'trapecija', 'Trapecija', 5),
  (7, '7-keturkampiai', 'transformacijos', 'Transformacijos', 6),
  (7, '7-plotai-ir-kiti-dydziai', 'trikampio', 'Trikampio', 1),
  (7, '7-plotai-ir-kiti-dydziai', 'lygiagretainio', 'Lygiagretainio', 2),
  (7, '7-plotai-ir-kiti-dydziai', 'trapecijos', 'Trapecijos', 3),
  (7, '7-plotai-ir-kiti-dydziai', 'apskritimo-ilgis-ir-skritulio-plotas', 'Apskritimo ilgis ir skritulio plotas', 4),
  (7, '7-plotai-ir-kiti-dydziai', 'ispjova-ir-lankas', 'Išpjova ir lankas', 5),
  (7, '7-stereometrija-3d', 'prizme', 'Prizmė', 1),
  (7, '7-stereometrija-3d', 'piramide', 'Piramidė', 2),
  (7, '7-stereometrija-3d', 'ritinys', 'Ritinys', 3),
  (7, '7-stereometrija-3d', 'kugis', 'Kūgis', 4),
  (8, '8-saknys', 'kvadratine-saknis', 'Kvadratinė šaknis', 1),
  (8, '8-saknys', 'kubine-saknis', 'Kubinė šaknis', 2),
  (8, '8-saknys', 'iracionalieji-skaiciai', 'Iracionalieji skaičiai', 3),
  (8, '8-saknys', 'palyginimas', 'Palyginimas', 4),
  (8, '8-saknys', 'sudetis-ir-atimtis', 'Sudėtis ir atimtis', 5),
  (8, '8-saknys', 'daugyba', 'Daugyba', 6),
  (8, '8-saknys', 'saknis-is-trupmenos', 'Šaknis iš trupmenos', 7),
  (8, '8-saknys', 'ikelimas-i-sakni-ir-iskelimas', 'Įkėlimas į šaknį ir iškėlimas', 8),
  (8, '8-saknys', 'skaitiniai-reiskiniai', 'Skaitiniai reiškiniai', 9),
  (8, '8-saknys', 'raidiniai-reiskiniai', 'Raidiniai reiškiniai', 10),
  (8, '8-vektoriai', 'vektorius-lygus-ir-priesingi', 'Vektorius. Lygūs ir priešingi', 1),
  (8, '8-vektoriai', 'sudetis-ir-atimtis', 'Sudėtis ir atimtis', 2),
  (8, '8-vektoriai', 'daugyba', 'Daugyba', 3),
  (8, '8-reiskiniai', 'raidiniai-reiskiniai', 'Raidiniai reiškiniai', 1),
  (8, '8-reiskiniai', 'greitosios-daugybos-formules', 'Greitosios daugybos formulės', 2),
  (8, '8-reiskiniai', 'skaidymas-dauginamaisiais', 'Skaidymas dauginamaisiais', 3),
  (8, '8-geometrija', 'pitagoro-teorema', 'Pitagoro teorema', 1),
  (8, '8-geometrija', 'vidurio-linija', 'Vidurio linija', 2),
  (8, '8-geometrija', 'trikampiai-ir-ju-savybes', 'Trikampiai ir jų savybės', 3),
  (8, '8-geometrija', 'perimetrai-ir-plotai', 'Perimetrai ir plotai', 4),
  (8, '8-lygciu-sistemos', 'lygtis-su-dviem-nezinomaisiais', 'Lygtis su dviem nežinomaisiais', 1),
  (8, '8-lygciu-sistemos', 'sistemu-sprendiniai', 'Sistemų sprendiniai', 2),
  (8, '8-lygciu-sistemos', 'grafinis-budas', 'Grafinis būdas', 3),
  (8, '8-lygciu-sistemos', 'keitimo-budas', 'Keitimo būdas', 4),
  (8, '8-lygciu-sistemos', 'sudeties-budas', 'Sudėties būdas', 5),
  (8, '8-lygciu-sistemos', 'sulyginimo-budas', 'Sulyginimo būdas', 6),
  (8, '8-lygciu-sistemos', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 7),
  (8, '8-stereometrija-3d', 'stacioji-prizme-ir-piramide', 'Stačioji prizmė ir piramidė', 1),
  (8, '8-stereometrija-3d', 'ritinys-ir-kugis', 'Ritinys ir kūgis', 2),
  (8, '8-stereometrija-3d', 'sfera-ir-rutulys', 'Sfera ir rutulys', 3),
  (8, '8-stereometrija-3d', 'pitagoro-teoremos-pritaikymas', 'Pitagoro teoremos pritaikymas', 4),
  (9, '9-kvadratines-lygtys', 'nepilnosios', 'Nepilnosios', 1),
  (9, '9-kvadratines-lygtys', 'pilnosios', 'Pilnosios', 2),
  (9, '9-kvadratines-lygtys', 'kvadratinio-trinario-skaidymas', 'Kvadratinio trinario skaidymas', 3),
  (9, '9-kvadratines-lygtys', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 4),
  (9, '9-lygciu-sistemos', 'sprendimas', 'Sprendimas', 1),
  (9, '9-lygciu-sistemos', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 2),
  (9, '9-trupmeniniai-reiskiniai', 'prastinimas-ir-apibrezimo-sritis', 'Prastinimas ir apibrėžimo sritis', 1),
  (9, '9-trupmeniniai-reiskiniai', 'sudetis-ir-atimtis', 'Sudėtis ir atimtis', 2),
  (9, '9-trupmeniniai-reiskiniai', 'daugyba-dalyba-kelimas-laipsniu', 'Daugyba, dalyba, kėlimas laipsniu', 3),
  (9, '9-trupmeniniai-reiskiniai', 'sudetingesniu-reiskiniu-sudarymas-ir-prastinimas', 'Sudėtingesnių reiškinių sudarymas ir prastinimas', 4),
  (9, '9-staciojo-trikampio-trigonometrija', 'trigonometrines-funkcijos', 'Trigonometrinės funkcijos', 1),
  (9, '9-staciojo-trikampio-trigonometrija', 'staciojo-trikampio-krastiniu-ir-kampu-skaiciavimas', 'Stačiojo trikampio kraštinių ir kampų skaičiavimas', 2),
  (9, '9-staciojo-trikampio-trigonometrija', 'trigonometrines-lygybes', 'Trigonometrinės lygybės', 3),
  (9, '9-staciojo-trikampio-trigonometrija', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 4),
  (9, '9-apskritimo-geometrija', 'centrinis-ir-ibreztinis-kampai', 'Centrinis ir įbrėžtinis kampai', 1),
  (9, '9-apskritimo-geometrija', 'liestine-ir-kirstine', 'Liestinė ir kirstinė', 2),
  (9, '9-apskritimo-geometrija', 'ispjova-ir-nuopjova', 'Išpjova ir nuopjova', 3),
  (9, '9-apskritimo-geometrija', 'laikrodziai', 'Laikrodžiai', 4),
  (9, '9-paprastos-funkcijos', 'ivairios-funkcijos', 'Įvairios funkcijos', 1),
  (9, '9-paprastos-funkcijos', 'tiesines-funkcijos', 'Tiesinės funkcijos', 2),
  (9, '9-kvadratines-funkcijos', 'ax2-c', 'ax2+c', 1),
  (9, '9-kvadratines-funkcijos', 'ax2-bx-c', 'ax2+bx+c', 2),
  (9, '9-kvadratines-funkcijos', 'a-x-m-2-n', 'a(x-m)2+n', 3),
  (9, '9-kvadratines-funkcijos', 'a-x-x1-x-x2', 'a(x-x1)(x-x2)', 4),
  (9, '9-kvadratines-funkcijos', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 5),
  (9, '9-kvadratines-funkcijos', 'grafinis-lygciu-sistemu-sprendimas', 'Grafinis lygčių sistemų sprendimas', 6),
  (10, '10-proporcingieji-dydziai', 'procentu-taikymo-uzdaviniai', 'Procentų taikymo uždaviniai', 1),
  (10, '10-proporcingieji-dydziai', 'sudetiniai-procentai', 'Sudėtiniai procentai', 2),
  (10, '10-racionaliosios-lygtys', 'racionaliuju-lygciu-sprendimas', 'Racionaliųjų lygčių sprendimas', 1),
  (10, '10-racionaliosios-lygtys', 'judejimo-uzdaviniai', 'Judėjimo uždaviniai', 2),
  (10, '10-racionaliosios-lygtys', 'darbo-uzdaviniai', 'Darbo uždaviniai', 3),
  (10, '10-racionaliosios-lygtys', 'kiti-tekstiniai-uzdaviniai', 'Kiti tekstiniai uždaviniai', 4),
  (10, '10-lygciu-sistemos', 'lygciu-sistemu-sprendimas', 'Lygčių sistemų sprendimas', 1),
  (10, '10-lygciu-sistemos', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 2),
  (10, '10-kvadratines-nelygybes', 'algebrinis-budas', 'Algebrinis būdas', 1),
  (10, '10-kvadratines-nelygybes', 'grafinis-budas', 'Grafinis būdas', 2),
  (10, '10-kvadratines-nelygybes', 'intervalu-budas', 'Intervalų būdas', 3),
  (10, '10-kvadratines-nelygybes', 'tekstiniai-uzdaviniai', 'Tekstiniai uždaviniai', 4),
  (10, '10-panasios-figuros', 'panasieji-trikampiai', 'Panašieji trikampiai', 1),
  (10, '10-panasios-figuros', 'panasiuju-trikampiu-perimetrai-ir-plotai', 'Panašiųjų trikampių perimetrai ir plotai', 2),
  (10, '10-panasios-figuros', 'pusiaukrastiniu-savybes', 'Pusiaukraštinių savybės', 3),
  (10, '10-panasios-figuros', 'pusiaukampiniu-savybe', 'Pusiaukampinių savybė', 4),
  (10, '10-panasios-figuros', 'panasieji-daugiakampiai', 'panašieji daugiakampiai', 5),
  (10, '10-ibreztiniai-ir-apibreztiniai', 'ibreztiniai-trikampiai', 'Įbrėžtiniai trikampiai', 1),
  (10, '10-ibreztiniai-ir-apibreztiniai', 'apibreztiniai-trikampiai', 'Apibrėžtiniai trikampiai', 2),
  (10, '10-ibreztiniai-ir-apibreztiniai', 'ibreztiniai-keturkampiai', 'Įbrėžtiniai keturkampiai', 3),
  (10, '10-ibreztiniai-ir-apibreztiniai', 'apibreztiniai-keturkampiai', 'Apibrėžtiniai keturkampiai', 4),
  (10, '10-trigonometrija', 'posukio-kampas', 'Posūkio kampas', 1),
  (10, '10-trigonometrija', 'trikampio-ploto-formule', 'Trikampio ploto formulė', 2),
  (10, '10-trigonometrija', 'sinusu-teorema', 'Sinusų teorema', 3),
  (10, '10-trigonometrija', 'kosinusu-teorema', 'Kosinusų teorema', 4),
  (10, '10-trigonometrija', 'gyvenimisko-turinio-uzdaviniai', 'Gyvenimiško turinio uždaviniai', 5),
  (10, '10-tikimybes-ir-kombinatorika', 'elementu-tvarka-svarbi', 'Elementų tvarka svarbi', 1),
  (10, '10-tikimybes-ir-kombinatorika', 'elementu-tvarka-nesvarbi', 'Elementų tvarka nesvarbi', 2),
  (10, '10-tikimybes-ir-kombinatorika', 'tikimybe', 'Tikimybė', 3),
  (11, '11-skaiciavimai', 'aibes', 'Aibės', 1),
  (11, '11-skaiciavimai', 'modulis', 'Modulis', 2),
  (11, '11-skaiciavimai', 'laipsniai-ir-saknys', 'Laipsniai ir šaknys', 3),
  (11, '11-skaiciavimai', 'logaritmai', 'Logaritmai', 4),
  (11, '11-trigonometriniai-skaiciavimai', 'posukio-kampas-sinusas-ir-kosinusas-vienetinis-apskriti', 'Posūkio kampas sinusas ir kosinusas. Vienetinis apskritimas', 1),
  (11, '11-trigonometriniai-skaiciavimai', 'arksinusas-ir-arkkosinusas', 'Arksinusas ir arkkosinusas', 2),
  (11, '11-trigonometriniai-skaiciavimai', 'tangentas-ir-jo-tiese-arktangentas', 'Tangentas ir jo tiesė, arktangentas', 3),
  (11, '11-progresijos', 'skaiciu-seka', 'Skaičių seka', 1),
  (11, '11-progresijos', 'aritmetine-progresija', 'Aritmetinė progresija', 2),
  (11, '11-progresijos', 'geometrine-progresija', 'Geometrinė progresija', 3),
  (11, '11-progresijos', 'nykstamoji-geometrine-progresija', 'Nykstamoji geometrinė progresija', 4),
  (11, '11-funkcijos', 'savybes', 'Savybės', 1),
  (11, '11-funkcijos', 'transformacijos', 'Transformacijos', 2),
  (11, '11-funkcijos', 'laipsnine', 'Laipsninė', 3),
  (11, '11-funkcijos', 'saknies', 'Šaknies', 4),
  (11, '11-funkcijos', 'rodikline', 'Rodiklinė', 5),
  (11, '11-funkcijos', 'logaritmine', 'Logaritminė', 6),
  (11, '11-funkcijos', 'trigonometrines', 'Trigonometrinės', 7),
  (11, '11-lygtys', 'su-parametru', 'Su parametru', 1),
  (11, '11-lygtys', 'iracionaliosios', 'Iracionaliosios', 2),
  (11, '11-lygtys', 'rodiklines', 'Rodiklinės', 3),
  (11, '11-lygtys', 'logaritmines', 'Logaritminės', 4),
  (11, '11-lygtys', 'su-moduliu', 'Su moduliu', 5),
  (11, '11-lygtys', 'lygciu-sistemos', 'Lygčių sistemos', 6),
  (11, '11-nelygybes', 'racionaliosios', 'Racionaliosios', 1),
  (11, '11-nelygybes', 'sistemos', 'Sistemos', 2),
  (11, '11-nelygybes', 'su-moduliu', 'Su moduliu', 3),
  (11, '11-nelygybes', 'rodiklines', 'Rodiklinės', 4),
  (11, '11-nelygybes', 'logaritmines', 'Logaritminės', 5),
  (12, '12-trigonometrija', 'tapatybes', 'Tapatybės', 1),
  (12, '12-trigonometrija', 'lygtys', 'Lygtys', 2),
  (12, '12-trigonometrija', 'nelygybes', 'Nelygybės', 3),
  (12, '12-isvestines', 'samprata-ir-ribos', 'Samprata ir ribos', 1),
  (12, '12-isvestines', 'isvestiniu-skaiciavimas', 'Išvestinių skaičiavimas', 2),
  (12, '12-isvestines', 'isvestiniu-pritaikymas', 'Išvestinių pritaikymas', 3),
  (12, '12-integralai', 'pirmykste-funkcija', 'Pirmykštė funkcija', 1),
  (12, '12-integralai', 'apibreztinis-integralas', 'Apibrėžtinis integralas', 2),
  (12, '12-integralai', 'plotai', 'Plotai', 3),
  (12, '12-integralai', 'turiai', 'Tūriai', 4),
  (12, '12-stereometrija-3d', 'tieses-ir-plokstumos', 'Tiesės ir plokštumos', 1),
  (12, '12-stereometrija-3d', 'briaunainiai', 'Briaunainiai', 2),
  (12, '12-stereometrija-3d', 'sukiniai', 'Sukiniai', 3),
  (12, '12-tikimybes-ir-kombinatorika', 'rinkiniai', 'Rinkiniai', 1),
  (12, '12-tikimybes-ir-kombinatorika', 'tikimybes', 'Tikimybės', 2),
  (12, '12-tikimybes-ir-kombinatorika', 'skirstiniai-ex-dx-ir-kt', 'Skirstiniai, EX, DX ir kt.', 3)
) AS s(grade, topic_slug, slug, title, ord)
  ON t.grade = s.grade AND t.slug = s.topic_slug
ON CONFLICT (topic_id, slug) DO UPDATE SET
  title = EXCLUDED.title,
  sort_order = EXCLUDED.sort_order;
